import YAML from "yaml";
import { z } from "zod";
import config from "../../site.config";

const base = `https://raw.githubusercontent.com/${config.contentRepo}/${config.contentBranch}`;
const SLUG = /^[\w-]+$/;

const EntrySchema = z.object({
  slug: z.string().regex(SLUG),
  title: z.string().min(1),
  date: z.string().optional(),
  tags: z.array(z.string()).default([]),
  excerpt: z.string().default(""),
});
export type Entry = z.infer<typeof EntrySchema>;

const FrontmatterSchema = z.object({
  title: z.string().min(1),
  date: z.coerce.string().optional(),
  tags: z.array(z.string()).default([]),
});

export interface Poem {
  slug: string;
  title: string;
  date?: string;
  tags: string[];
  /** Each stanza is a string with its line breaks and indentation intact */
  stanzas: string[];
}

/** List of all poems, newest first. Generated by the Action in the content repo. */
export async function getIndex(): Promise<Entry[]> {
  const res = await fetch(`${base}/index.json`);
  if (!res.ok) {
    throw new Error(`Could not load index.json from ${config.contentRepo} (HTTP ${res.status}).`);
  }
  const data = await res.json();
  if (!Array.isArray(data)) throw new Error("index.json must be a list of poems.");
  return data
    .flatMap((item) => {
      const parsed = EntrySchema.safeParse(item);
      return parsed.success ? [parsed.data] : [];
    })
    .sort((a, b) => (b.date ?? "").localeCompare(a.date ?? ""));
}

/** One poem, or null if it doesn't exist. */
export async function getPoem(slug: string): Promise<Poem | null> {
  if (!SLUG.test(slug)) return null;
  const res = await fetch(`${base}/poems/${slug}.md`);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`Could not load "${slug}" (HTTP ${res.status}).`);

  const raw = (await res.text()).replace(/^\uFEFF/, "").replace(/\r\n/g, "\n");
  const match = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!match) return null;

  const meta = FrontmatterSchema.safeParse(YAML.parse(match[1]) ?? {});
  if (!meta.success) return null;

  // Treat the body as plain text, not Markdown, so spacing and indentation survive.
  const body = match[2].replace(/^\n+/, "").trimEnd();
  const stanzas = body.split(/\n[ \t]*\n(?:[ \t]*\n)*/).filter((s) => s.trim().length > 0);

  return { slug, ...meta.data, stanzas };
}

/** Short plain-text summary for meta descriptions */
export function summarize(stanzas: string[], max = 160): string {
  const flat = stanzas.join(" ").replace(/\s+/g, " ").trim();
  if (flat.length <= max) return flat;
  return flat.slice(0, max).replace(/\s+\S*$/, "") + "…";
}
